*;
*MOST FREQUENT VALUE (COUNT);
*;
length IMP_JOB $7;
label IMP_JOB = 'Imputed JOB';
IMP_JOB = JOB;
if JOB = '' then IMP_JOB = 'Other';
length IMP_REASON $7;
label IMP_REASON = 'Imputed REASON';
IMP_REASON = REASON;
if REASON = '' then IMP_REASON = 'DebtCon';
*;
*MEAN-MAX-MIN-MEDIAN-MIDRANGE AND ROBUST ESTIMATES;
*;
label IMP_REP_CLAGE = 'Imputed: Replacement: CLAGE';
length IMP_REP_CLAGE 8;
IMP_REP_CLAGE = REP_CLAGE;
if missing(REP_CLAGE) then IMP_REP_CLAGE = 178.17673018;
label IMP_REP_CLNO = 'Imputed: Replacement: CLNO';
length IMP_REP_CLNO 8;
IMP_REP_CLNO = REP_CLNO;
if missing(REP_CLNO) then IMP_REP_CLNO = 21.279396672;
label IMP_REP_DEBTINC = 'Imputed: Replacement: DEBTINC';
length IMP_REP_DEBTINC 8;
IMP_REP_DEBTINC = REP_DEBTINC;
if missing(REP_DEBTINC) then IMP_REP_DEBTINC = 33.666534932;
label IMP_REP_DELINQ = 'Imputed: Replacement: DELINQ';
length IMP_REP_DELINQ 8;
IMP_REP_DELINQ = REP_DELINQ;
if missing(REP_DELINQ) then IMP_REP_DELINQ = 0.4240816807;
label IMP_REP_DEROG = 'Imputed: Replacement: DEROG';
length IMP_REP_DEROG 8;
IMP_REP_DEROG = REP_DEROG;
if missing(REP_DEROG) then IMP_REP_DEROG = 0.2116898639;
label IMP_REP_MORTDUE = 'Imputed: Replacement: MORTDUE';
length IMP_REP_MORTDUE 8;
IMP_REP_MORTDUE = REP_MORTDUE;
if missing(REP_MORTDUE) then IMP_REP_MORTDUE = 73441.205876;
label IMP_REP_NINQ = 'Imputed: Replacement: NINQ';
length IMP_REP_NINQ 8;
IMP_REP_NINQ = REP_NINQ;
if missing(REP_NINQ) then IMP_REP_NINQ = 1.1352467601;
label IMP_REP_VALUE = 'Imputed: Replacement: VALUE';
length IMP_REP_VALUE 8;
IMP_REP_VALUE = REP_VALUE;
if missing(REP_VALUE) then IMP_REP_VALUE = 101363.22276;
label IMP_REP_YOJ = 'Imputed: Replacement: YOJ';
length IMP_REP_YOJ 8;
IMP_REP_YOJ = REP_YOJ;
if missing(REP_YOJ) then IMP_REP_YOJ = 8.8683676788;
